"use client";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import Link from "next/link";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { LyricsPreview } from "@/components/shared/LyricsPreview";
import { ApprovalPanel } from "@/components/shared/ApprovalPanel";
import { listSongs } from "@/lib/api-client";
import type { ArtistId, CoverStatus, SongDraft } from "@/lib/types";

export default function SongsPage() {
  const [artistId, setArtistId] = useState<ArtistId>("aarav");

  const { data: songs, isLoading } = useQuery({
    queryKey: ["songs", artistId],
    queryFn: () => listSongs(artistId),
  });

  return (
    <main className="p-8 max-w-5xl mx-auto space-y-6">
      <div>
        <Link href="/" className="text-xs text-gray-500 hover:text-gray-300">← Dashboard</Link>
        <h1 className="text-2xl font-bold text-white mt-2">Original Songs</h1>
        <p className="text-sm text-gray-400 mt-1">Songs generated by the pipeline</p>
      </div>

      {/* Artist tabs */}
      <div className="flex gap-3">
        {(["aarav", "aarohi"] as ArtistId[]).map((id) => (
          <button
            key={id}
            onClick={() => setArtistId(id)}
            className={`rounded-lg px-5 py-2 text-sm font-medium transition-colors ${
              artistId === id
                ? id === "aarav"
                  ? "bg-[#e94560] text-white"
                  : "bg-[#8B6914] text-white"
                : "bg-white/10 text-gray-400 hover:bg-white/15"
            }`}
          >
            {id === "aarav" ? "Aarav" : "Aarohi"}
            {songs && artistId === id && (
              <span className="ml-2 text-xs opacity-70">{songs.length}</span>
            )}
          </button>
        ))}
      </div>

      {/* Song list */}
      {isLoading ? (
        <p className="text-sm text-gray-500">Loading…</p>
      ) : !songs || songs.length === 0 ? (
        <div className="rounded-xl border border-white/10 bg-white/5 p-8 text-center">
          <p className="text-gray-400 text-sm">No songs yet.</p>
          <p className="text-gray-600 text-xs mt-1">
            Use the{" "}
            <Link href="/pipeline" className="text-blue-400 underline">
              Pipeline page
            </Link>{" "}
            to generate your first song.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {songs.map((song) => (
            <SongCard key={song.job_id} song={song} artistId={artistId} />
          ))}
        </div>
      )}
    </main>
  );
}

function SongCard({ song, artistId }: { song: SongDraft; artistId: ArtistId }) {
  const queryClient = useQueryClient();
  const [expanded, setExpanded] = useState(false);
  const [approving, setApproving] = useState(false);

  const status = (song.status === "phase1_complete" || song.status === "completed_phase1"
    ? "awaiting_approval"
    : song.status === "phase2_complete" || song.status === "completed_phase2"
    ? "published"
    : song.status === "failed"
    ? "failed"
    : "generating") as CoverStatus;

  const handleDecision = () => {
    setApproving(false);
    queryClient.invalidateQueries({ queryKey: ["songs", artistId] });
  };

  return (
    <div className="rounded-xl border border-white/10 bg-white/5 overflow-hidden">
      {/* Header row */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between gap-4 p-4 text-left hover:bg-white/5 transition-colors"
      >
        <div className="min-w-0">
          <p className="font-medium text-white truncate">{song.song_title}</p>
          {song.lyrics.hook_line && (
            <p className="text-xs text-gray-400 mt-0.5 italic truncate">"{song.lyrics.hook_line}"</p>
          )}
        </div>
        <div className="flex items-center gap-3 flex-shrink-0">
          <StatusBadge status={status} />
          <span className="text-gray-600 text-xs">{expanded ? "▲" : "▼"}</span>
        </div>
      </button>

      {/* Mood tags */}
      {song.lyrics.mood_tags.length > 0 && (
        <div className="px-4 pb-3 flex flex-wrap gap-1.5">
          {song.lyrics.mood_tags.map((tag) => (
            <span key={tag} className="rounded-full bg-white/10 px-2 py-0.5 text-[10px] text-gray-400">
              {tag}
            </span>
          ))}
          {song.metadata.seo_score > 0 && (
            <span className="ml-auto text-[10px] text-gray-600">SEO {song.metadata.seo_score}/100</span>
          )}
        </div>
      )}

      {/* Expanded: lyrics + approval */}
      {expanded && (
        <div className="border-t border-white/10 p-4 space-y-4">
          {/* YouTube title */}
          <div>
            <p className="text-[10px] text-gray-500 uppercase tracking-wide mb-1">YouTube Title</p>
            <p className="text-xs text-gray-300 bg-black/30 rounded p-2">{song.metadata.title}</p>
          </div>

          {/* Lyrics */}
          <div>
            <p className="text-[10px] text-gray-500 uppercase tracking-wide mb-2">Lyrics</p>
            <div className="max-h-60 overflow-y-auto rounded bg-black/30 p-3">
              <LyricsPreview lyricsText={song.lyrics.lyrics_text} />
            </div>
          </div>

          {/* Approval panel for phase1_complete songs */}
          {(song.status === "phase1_complete" || song.status === "completed_phase1") && (
            <div>
              {!approving ? (
                <button
                  onClick={() => setApproving(true)}
                  className="rounded px-4 py-2 text-sm font-medium bg-green-800 hover:bg-green-700 text-white transition-colors"
                >
                  Review &amp; Approve
                </button>
              ) : (
                <ApprovalPanel
                  jobId={song.job_id}
                  songTitle={song.song_title}
                  onDecision={handleDecision}
                />
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
